package chen.shanmugarajah;

public enum CarParkedLocation {
	CARPORT,
	DRIVEWAY,
	ROAD_HOME,
	ROAD_AWAY,
	LOCKED_GARAGE,
	UNLOCKED_GARAGE,
	WORK_CARPARK,
	RESIDENTIAL_CARPARK,
	SECURE_CARPARK,
	FORCES_CARPARK,
	UNSECURE_CARPARK,
	RAILWAY_CARPARK
}
