package chen.shanmugarajah;

public enum CarUsage {
	SOCIAL_ONLY,
	SOCIAL_INCLUDING_COMMUTE,
	BUSINESS_USE_BY_YOU,
	BUSINESS_USE_BY_YOU_AND_PARTNER,
	BUSINESS_USE_BY_PARTNER,
	BUSINESS_USE_BY_ALL,
	COMMERCIAL_TRAVELLING
}
